### ISSUE TITLE
Some information for extrastuff/resources.md

### ISSUE THREAD

**Issue by BobWall23** [timtiemens/secretshare#3]
In your discussion about 'ssss', you question why it defines add as XOR and imply that the values it computes for the splits are incorrect.

I wanted to point out that the ssss implementation uses GF(2^n), where n is the number of bits in the secret, instead of using GF(p), where p is some prime. This is not invalid - since 2 is prime, it is possible to construct a finite field of order 2^n for n > 1. In an extension of GF(2), addition is the same as addition in GF(2), which is XOR. Multiplication is a little different - it requires the use of an irreducible polynomial of the appropriate degree (hence the irred_coeff array). So I don't think it is necessarily computing the wrong value. See https://en.wikipedia.org/wiki/Finite_field#Non-prime_fields for details.

Regarding it coming up with different a different result when you try to combine its output: since it is using a different modulus, I would expect it to come up with a different combined value. If you recompiled your program to use a different prime for the modulus and ran it with the same inputs, it would come up with different splits as well. If you put some subset of those splits back into your original program, it would compute a different value for the original secret (since it is doing modulo p arithmetic).

**Comment by timtiemens** [comment]
I'll admit my last comment was a bit harsh given the evidence.

However, the bulk of my comments center around "don't trust things you don't understand".  

Since your comments on the subject conclude with the endorsement "I don't think it is necessarily computing the wrong value", I'll stand by my assessment of ssss.  My endorsement was a little better with "it is internally consistent" -- i.e. use ssss to generate your shares, and only use ssss to rebuild your secret, do not cross the two systems.

Which is sad, since I really do want to find another program that SecretShareInJava can successfully inter-operate against.
