### ISSUE TITLE
How to generate additional shares

### ISSUE THREAD

**Issue by willitrace** [timtiemens/secretshare#4]
I have generated shares and I would like to add additional shares to scheme.
For example I have defined 2 of 4 scheme and generated 4 shares using the following:

```
SecretShare.PublicInfo publicInfo = new SecretShare.PublicInfo(4, 2, PRIME_MODULUS, "");
SecretShare secretShare = new SecretShare(publicInfo);
SecretShare.SplitSecretOutput generate = secretShare.split(new BigInteger(1, pin.getBytes()), new Random());		
List<SecretShare.ShareInfo> shares = generate.getShareInfos();
```

Now I would like to add additional 5th share. How to do it?
In order to reconstruct polynomial and secret I can do the following:

```
SecretShare.PublicInfo combineInfo = new SecretShare.PublicInfo(null, reqPins, PRIME_MODULUS, "");
SecretShare combineShare = new SecretShare(combineInfo);
        
SecretShare.ShareInfo one = new SecretShare.ShareInfo(1, new BigInteger(1, Utils.hexStringToByteArray("XXXXXXXXXXXXXXXX")), combineInfo);
SecretShare.ShareInfo two = new SecretShare.ShareInfo(2, new BigInteger(1, Utils.hexStringToByteArray("XXXXXXXXXXXXXXXX")), combineInfo);
List<SecretShare.ShareInfo> combineShares = new ArrayList<SecretShare.ShareInfo>();
combineShares.add(one);
combineShares.add(two);
        
SecretShare.CombineOutput combine = combineShare.combine(combineShares);
String combined = new String(combine.getSecret().toByteArray());
```

But how can I use this in order to generate additional share and to be able to use it with others already generated?
If I use the generated again it would apparently work because of different generator.

**Comment by timtiemens** [comment]
The branch experiment/generate-more-shares shows the code required to implement this feature.
https://github.com/timtiemens/secretshare/tree/experiment/generate-more-shares

At a high level, the design requires two changes:  1) make 'combine' store the coefficients and 2) create a new 'split' entry point that accepts the coefficients as input instead of creating random ones.

First, check out the branch experiment/generate-more-shares.  
Then, see src/test/java/com/tiemens/secretshare/engine/GenerateMoreSharesTest.java

This code will not be merged to master because:
1) to make this really work would require command-line changes - currently there is 'split' and 'combine' -- this would require a confusing 'combineAndSplit' option
2) the changes break some typing boundaries (i.e. a generic T is assumed to be a BigInteger)
3) Assuming a BigInteger does not work in all cases, because the combiner is free to use BigRational.
