### ISSUE TITLE
Error reporting on the specific share failing

### ISSUE THREAD

**Issue by jaromil** [timtiemens/secretshare#5]
Hi there! first of all thanks for your fine implementation of secret sharing! I'm using it in https://github.com/dyne/FXC which can be considered an encapsulation protocol and a demonstration of it is visible here https://secrets.dyne.org

I have a question about your library: in case of failure to combine the shares, is it possible to report which share contains errors? I sort of think is not possible, but I'm not such a good mathematician to be sure of this and would like to hear your own opinion about it as you implemented this algorithm. Thanks!

**Comment by timtiemens** [comment]
My opinion only matters for how to interpret your question.  For certain interpretations, there is no opinion, just the math.  Here are a series of answers to your question (depending on how the question is interpreted):
 
1) The algorithm never fails to combine the shares.  Given K "distinct" shares and a modulus, it will always give you the secret specified by those K shares.  There is never a failure.

2) The algorithm will not give you the secret that you expected if you enter the wrong share(s).  The two sub-cases are:

2a) If you gave it exactly K of K shares, there is no way to determine which share is "wrong" - because they are all equally right and wrong.  There is no partial information available from any K-1 size subset.

2b) If you have "extra" shares (say "b" shares, b > K), then it is possible to loop over all of the size K subsets of your b shares, and declare the "winning secret" to be the secret computed most often. The number of subsets size K from b choices is the formula   (b! / (k! * (b-k)!)).  For b=5 shares and K=4,that means 5 calculations.  For b=15 shares and K=5, that means 3,003 calculations.


As a side note on the issue of typos in the share: you'll notice that every share is printed twice:  once formatted as a normal integer and once formatted as a "bigintcs" (big integer check sum), like so:
Share (x:1) = 7802163
Share (x:1) = bigintcs:770d33-D03372
This becomes the 3rd answer:
3) When you combine shares using bigintcs formatted numbers, the application will alert you to typos, so you will know exactly which shares have been entered incorrectly.

**Comment by timtiemens** [comment]
The branch "feature/paranoidcombine" has code that implements a "-paranoid" argument for the "combine" operation.   This option should be able to help solve your real-world "corrupt share" problem.  It will also let you experiment with your original question: you can mangle the share value(s), and let combine -paranoid compute many secrets from the subsets.

**Comment by jaromil** [comment]
many thanks Tim! you did interpret very well my question, I will test the paranoid it and report here the results. This may lead to a new more robust version of the FXC protocol. It will take me a while, also depending from use-cases explicitly requiring this feature. One may be brewing here https://github.com/gdassori/ssshare

**Comment by timtiemens** [comment]
Released secretshare 1.4.3 with the -paranoid option

**Comment by timtiemens** [comment]
(Just in case others visit this thread).

Per the "2a" above, in my long comment above, there is no way to report the faulty share, because all shares are equal.  There is no "global secret information" inside a share.  A share is a piece of the solution, and the pieces do not overlap.

Asking to "report faulty share" is akin to asking which of these is faulty:

- x = 5
- x = 7
- x = 9

It can't be done, because none of those is "faulty".

The best that can be done has already been implemented - if you have extra shares, you can perform multiple "combine" operations on different subsets of your shares, and from that, possibly determine which share is "faulty".

I encourage those interested to run "combine" operations on "random" values, e.g.
`java -jar secretshare.jar combine -k 3 -s1 5 -s2 7 -s3 13 -s4 17 
             -paranoid maxCombinationsAllowedToTest=50000`
You will see that the secret can be 7, or 5, or 1, or a 117-digit number.  
The math works for all 4 secrets.
